version: "2.1"
services:
  # Needs changes to your DHCP server to work correctly.
  # See https://hub.docker.com/r/linuxserver/netbootxyz
  netbootxyz:
    container_name: netbootxyz
    environment:
      - PUID=1001
      - PGID=1000
      - TZ=America/Los_Angeles
    hostname: cineplex
    image: lscr.io/linuxserver/netbootxyz:latest
    ports:
      - 69:69/udp
      - 3000:3000
    restart: unless-stopped
    volumes:
      - /share/Container/netbootxyz:/config

  tautulli:
    container_name: tautulli
    environment:
      - PUID=1001
      - PGID=1000
      - TZ=America/Los_Angeles
    hostname: cineplex
    image: lscr.io/linuxserver/tautulli
    ports:
      - "8181:8181"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/Container/tautulli:/config
      - /share/Container/plex/Library/Application Support/Plex Media Server/Logs:/logs

  channels-dvr:
    container_name: channels-dvr
    devices:
      - /dev/dri:/dev/dri
    hostname: cineplex
    image: fancybits/channels-dvr:latest
    # By using bridge networking we give up mDNS
    # network_mode: host
    ports:
      # Channels-DVR enables mDNS by default so that client apps can find
      # the server automagically.  We're specifically disabling Zeroconf
      # so all clients need to manually set an IP address to access the 
      # server.
      # - "5353:5353/udp" # (Bonjour/Avahi/Zeroconf network discovery)
      - "8089:8089"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/Container/channels-dvr:/channels-dvr
      - /share/Media/video:/shares/DVR

  prowlarr:
    container_name: prowlarr
    environment:
      - PUID=1001
      - PGID=1000
      - TZ=America/Los_Angeles
    hostname: cineplex
    image: lscr.io/linuxserver/prowlarr
    ports:
      - 9696:9696
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/Container/prowlarr:/config

  makemkv:
    container_name: makemkv
    environment:
      - USER_ID=1000
      - GROUP_ID=1001
      - TZ=America/Los_Angeles
    hostname: cineplex
    image: jlesage/makemkv
    ports:
      - 5800:5800
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/Container/makemkv:/config
      - /share/Media:/media
      - /share/Download/sabnzbd/completed:/download

#  recyclarr:
#    container_name: recyclarr
#    environment:
#      - TZ=America/Los_Angeles
#      - RECYCLARR_CREATE_CONFIG=true
#    hostname: cineplex
#    image: lscr.io/recyclarr/recyclarr
#    restart: unless-stopped
#    user: 1001:1000
#    volumes:
#    - /etc/localtime:/etc/localtime:ro
#    - /share/Container/recyclarr:/config

  sabnzbd:
    container_name: sabnzbd
    environment:
      - PUID=1001
      - PGID=1000
      - TZ=America/Los_Angeles
    hostname: cineplex
    image: lscr.io/linuxserver/sabnzbd
    ports:
      - 4444:8080
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/Container/sabnzbd:/config
      - /share/Download/sabnzbd:/download
      - /share/Backup/sabnzbd:/backup

  radarr:
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=1000
      - TZ=America/Los_Angeles
    hostname: cineplex
    image: lscr.io/linuxserver/radarr
    ports:
      - 7878:7878
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/Container/radarr:/config
      - /share/Media/movies:/movies
      - /share/Download/sabnzbd/completed/movies:/download

  sonarr:
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1000
      - TZ=America/Los_Angeles
    hostname: cineplex
    image: lscr.io/linuxserver/sonarr
    ports:
      - 8989:8989
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/Container/sonarr:/config
      - /share/Media/series:/series
      - /share/Download/sabnzbd/completed/series:/download

  lidarr:
    container_name: lidarr
    environment:
      - PUID=1001
      - PGID=1000
      - TZ=America/Los_Angeles
    hostname: cineplex
    image: lscr.io/linuxserver/lidarr
    ports:
      - 8686:8686
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/Container/lidarr:/config
      - /share/Media/music:/music
      - /share/Download/sabnzbd/completed/music:/download

  portainer:
    command:
      - -H
      - unix:///var/run/docker.sock
    container_name: portainer
    environment:
      - TZ=America/Los_Angeles
    hostname: cineplex
    image: portainer/portainer-ce
    ports:
      - 8000:8000
      - 9000:9000
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/Container/portainer:/config
      - /var/run/docker.sock:/var/run/docker.sock

  plex:
    container_name: plex
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1001
      - PGID=1000
      - TZ=America/Los_Angeles
      - VERSION=docker
    hostname: cineplex
    image: lscr.io/linuxserver/plex
    ports:
      # Port listing from Plex website as of 2023-04-11.
      # https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/
      - "32400:32400"     # (for access to the Plex Media Server) [required]
      # - "1900:1900/udp" # (access to the Plex DLNA Server)
      # - "5353:5353/udp" # (older Bonjour/Avahi network discovery)
      # - "8324:8324"     # (controlling Plex for Roku via Plex Companion)
      - "32410:32410/udp" # (current GDM network discovery)
      - "32412:32412/udp" # (current GDM network discovery)
      - "32413:32413/udp" # (current GDM network discovery)
      - "32414:32414/udp" # (current GDM network discovery)
      # - "32469:32469"   # (access to the Plex DLNA Server)
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/Backup/plex:/backup
      - /share/Container/plex:/config
      - /share/Media/movies:/movies:ro
      - /share/Media/music:/music:ro
      - /share/Media/series:/series:ro
      - /share/Media/video:/video:ro
